travis:
  secure:
    BINSTAR_TOKEN: NVoI32dCdvJdpYxq04U511nL0QiVJRNgWqV1SaR1/uD9O1x3x0z84MZum6Y4x49LM9kmUGnaNrh8lXRYRwAwNkNL7pmYvLA8M23fxsvqPoS9euzZ09OvLHXrMgq2surs5hp+4pu0FtgfuVCj4ZjPeehS3oySnDP+qIeYlEuGGDvQ96OziTDDmEWwC1Xo0ARulOAIRbDaN1OSQ4vW13kfyqwQtts9JdvQAvDBLpcc8/e5HHnAdzfUeA+njpHDCEgUHZ37Idj8yNg4A5OWtgvXf+sLpTNCnWf/HEhGy51jAB9Qpqro8aAmjwZd2gvUkY/A5lZrvFr90mACB6Fmpw/gLRgX5W6AFqh3lcj/Y4/VpHY/ArekNslPeKZp0tTSvyy3nmqeEjSGAEPv4e4E4d0A5DUDRubzWac0Xy/pjbK7v1cEhNd6S/CFYJS5qDmnO08+t/vaSCQ2munqLU52jnq72YJomcgN3VSLE7etAqPdEj/QZuztl3EqwDfvwNpbY9LzLL5AGKzsQLOnA1NOlmyDntLt+qy1cLVpBQg/JZLhItR/iXcjxnwlelkMTx3lz3WLoNAwzXUGoBcXJas/m4fhK4vb4reb4XxMGNEz/UNp7AhSCZ2iOUJFd/sHnbgFlLE2/cMDUfVq9riasW4dSzX8vKt+9vrHultg0y73ukPGzqY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
